version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
    reviewers:
      - 'TalusStudio/Dev-Backend'
    assignees:
      - 'TalusCI'

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "php"
    reviewers:
      - 'TalusStudio/Dev-Backend'
    assignees:
      - 'TalusCI'

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "javascript-livewire"
    reviewers:
      - 'TalusStudio/Dev-Backend'
    assignees:
      - 'TalusCI'
