hosts:
  staging:
    labels:
      env: staging
    hostname: '52.30.195.144'
    remote_user: ubuntu
    deploy_path: '/var/www/html/{{application}}'
    branch: dev
    composer_options: '--verbose --prefer-dist --no-interaction --no-scripts --optimize-autoloader'

  production:
    labels:
      env: production
    hostname: '34.252.141.173'
    remote_user: ubuntu
    deploy_path: '/var/www/html/{{application}}'
    branch: master
    composer_options: '--verbose --prefer-dist --no-interaction --no-scripts --no-dev --optimize-autoloader'
