name: deploy-prod

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed

concurrency: production_environment

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis

      - name: Setup Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 5

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts

      - name: Install NPM Dependencies
        run: npm ci

      - name: Compile Assets
        run: npm run production

      - name: Environment File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: .env
          write-mode: overwrite
          contents: ${{ secrets.DOTENV }}

      - name: Deploy
        uses: deployphp/action@v1.0.22
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy env=production -vvv

      - name: Create Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: 'ChimpDelivery'
          SENTRY_PROJECT: 'chimpdelivery'
        with:
          environment: production
          set_commits: auto
          ignore_empty: true
