name: deploy-staging-test

on:
  push:
    branches: [dev]

env:
  SENTRY_ORG: talusstudio
  SENTRY_PROJECT: talus-dashboard
  VERSION: "sentry-cli releases propose-version"

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    steps:
      - uses: actions/checkout@v3

      - name: REST API with curl
        run: |
          curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.2.0" bash
          
      - name: Notify
        run: sentry-cli releases new "$VERSION" &&
             sentry-cli releases set-commits "$VERSION" --auto &&
             sentry-cli releases finalize "$VERSION"
